advanced/backend/models/Comment.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "comment".
 *
 * @property integer $id_com
 * @property integer $id_news
 * @property integer $id_last
 * @property string $date_cr
 * @property string $date_ed
 * @property integer $user
 * @property integer $ident
 * @property string $email
 * @property string $text
 * @property integer $mod
 *
 * @property News $idNews
 * @property User $user0
 */
class Comment extends \yii\db\ActiveRecord
{
    public static $id_new;
    public static $id_coment;
    public static $com_width = 900;
    const STATUS_ENABLED = 1;
    const STATUS_DISABLED = 0;
    

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'comment';
    }

    /**
     * @inheritdoc
     */
     public function rules()
    {
        return [
            [[
                'id_news',
                'id_last', 'username', 'email', 'text',], 'required'],
            [['id_news', 'id_last', 'status', ], 'integer'],
            [['date_cr', ], 'safe'],
            [['email', 'text', 'username', 'ip'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
     public function attributeLabels()
    {
        return [
            'id_com' => 'ID Коментара',
            'id_news' => 'ID Новини',
            'id_last' => 'ID Батьківський',
            'username' => 'Логін',
            'email' => 'Email',
            'text' => 'Текст коментара',
            'status' => 'Статус',
            'ip' => 'IP',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdNews()
    {
        return $this->hasOne(News::className(), ['id_news' => 'id_news']);
    }
    public function getIdCrdate()
    {
        return $this->hasOne(News::className(), ['crdate' => 'crdate']);
    }
   // public $getForm = render('_form'); 
    

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser0()
    {
        return $this->hasOne(User::className(), ['username' => 'username']);
    }
}

advanced/frontend/models/Comment.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "comment".
 *
 * @property integer $id_com
 * @property integer $id_news
 * @property integer $id_last
 * @property string $date_cr
 * @property string $date_ed
 * @property integer $user
 * @property integer $ident
 * @property string $email
 * @property string $text
 * @property integer $mod
 *
 * @property News $idNews
 * @property User $user0
 */
class Comment extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'comment';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_news', 'id_last', 'username', 'email', 'text'], 'required'],
            [['id_news', 'id_last',  ], 'integer'],
            [['date_cr', ], 'safe'],
            [['email', 'text', 'username'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_com' => 'Id Com',
            'id_news' => 'Id News',
            'id_last' => 'Id Last',
            'username' => 'Username',
            'email' => 'Email',
            'text' => 'Text',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdNews()
    {
        return $this->hasOne(News::className(), ['id_news' => 'id_news']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser0()
    {
        return $this->hasOne(User::className(), ['username' => 'username']);
    }
}

advanced/backend/controllers/CommentController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Comment;
use backend\models\CommentSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CommentController implements the CRUD actions for Comment model.
 */
class CommentController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }


    public function actionIndex() {

        if (Yii::$app->request->isAjax and Yii::$app->request->isPost) {
            $this->enableCsrfValidation = false;
            $post = Yii::$app->request->post();
            $notes = $post['notes'];
            foreach ($notes as $id => $text) {

                $model = Comment::findOne($id);
                $model->text = $text;
//                $x=$_SERVER['REMOTE_ADDR'];
//                echo $x;
//                exit;
                $model->save();
            }
            echo \yii\helpers\Json::encode([
                'output' => '',
                'message' => !empty($model->hasErrors()) ? 'Помилка' : '',
            ]);

            return;
        }

        if (empty($searchModel->id_news)) {
            $searchModel = new CommentSearch();
        } else {
            $searchModel = CommentSearch::findOne($model->id_news);
        }
        $model = new \backend\models\Comment();
        $model->ip = $_SERVER['REMOTE_ADDR'];
       
        $params = Yii::$app->request->queryParams;
        $searchModel->load($params);
        $comments = '';


        if (!empty($params['CommentSearch']['id_news'])) {

            \backend\models\Comment::$id_new = $params['CommentSearch']['id_news'];

            $writecom = \backend\models\CommentSearch::commentFromNews();

            $comments = $this->renderPartial('comments', [
                'dataProvider' => $writecom,
            ]);
        }
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
//            $model->id_news = \backend\models\Comment::$id_new;
            $model->save();
//            return $this->redirect(['index', 'searchModel' => $searchModel]);
            return $this->refresh();
        } else {
            return $this->render('index', [
                        'comments' => $comments,
                        'searchModel' => $searchModel,
                        'id_news' => Comment::$id_new,
            ]);
        }
    }


    protected function findModel($id) {
        if (($model = Comment::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionGetinfo() {


        if (!isset($_POST['comment_id']) || empty($_POST['comment_id']))
            return;
        $comment_id = $_POST['comment_id'];
        $model = Comment::findOne($comment_id);
        $model->status = $model->status == Comment::STATUS_DISABLED ? Comment::STATUS_ENABLED : Comment::STATUS_DISABLED;
        $model->save();

        return $model->status;
    }

}

advanced/frontend/controllers/CommentController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Comment;
use frontend\models\CommentSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CommentController implements the CRUD actions for Comment model.
 */
class CommentController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Comment models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new CommentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Comment model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Comment model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Comment();

        if ($model->load(Yii::$app->request->post())
               && $model->save()
                ) {



            $model->save();
          //  echo '<pre>';
          //  print_r($model->getErrors());
          //  echo '</pre>';
           // echo '<pre>';
           // print_r(Yii::$app->request->post());
          //  echo '</pre>';
          //  return $this->redirect(['view', 'id_com' => $id_com]);
            return $this->redirect(['view', 'id' => $model->id_com]);
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    public function actionAddCom() {
        $model = new \models\Comment();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {



         
            return $this->redirect(['view', 'id' => $model->id_com]);
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Comment model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {


            $model->save();
            return $this->redirect(['view', 'id' => $model->id_com]);
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Comment model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Comment model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Comment the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Comment::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

advanced/backend/views/comment/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Comment */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="comment-form">

    <?php $form = ActiveForm::begin(); ?>
    <?php // echo $form->field($model, 'id_last')->textInput() ?>
    <?php // echo $form->field($model, 'date_cr')->textInput() ?>
    <?php //echo $form->field($model, 'date_ed')->textInput() ?>    
    <?php //echo $form->field($model, 'mod')->textInput() ?>    

    <?php // echo $form->field($model, 'id_news')->textInput() ?>



    <?php // echo $form->field($model, 'ident')->textInput() ?>    

    <table style="text-align: left; width: 100%;" border="0"
           cellpadding="2" cellspacing="2">
        <tbody>
            <tr>
                <td style="width: 100px; text-align: left;"></td>
                <td style="text-align: left;">
                    <?php echo $form->field($model, 'username')->textInput() ?>
                </td>
                <td style="width: 100px; text-align: center;"></td>
            </tr>
            <tr>
                <td style="text-align: left;"></td>
                <td style="text-align: left;">
                    <?php echo $form->field($model, 'email')->textInput() ?>
                </td>
                <td style="text-align: center;"></td>
            </tr>
            <tr>
                <td style="text-align: left;" colspan="3"
                    rowspan="1">
                        <?php echo $form->field($model, 'text')->textarea(['rows' => 6]) ?> 
                </td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td style="text-align: center;">
                    <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                </td>
            </tr>
        </tbody>
    </table>




    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

advanced/backend/views/comment/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;

?>

<div class="comment-search">

    <?php
    $form = ActiveForm::begin([
                'action' => ['index'],
                'method' => 'get',
    ]);
    echo
    $form->field($model, 'id_news')->widget(Select2::classname(), [
        'data' => yii\helpers\ArrayHelper::map(\backend\models\News::find()
                        ->orderBy(['crdate' => SORT_DESC])
                        ->asArray()
                        ->all()
                , 'id_news'
                , 'name'),
        'language' => 'ru',
        'options' => ['placeholder' => 'Оберіть Новину...'],
        'pluginOptions' => [
            'allowClear' => TRUE
        ],
    ]);
    ?>
    <div class="form-group">
        <?= Html::submitButton('Пошук коментарів', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

advanced/backend/views/comment/addcom.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Comment */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="comment-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php
    //if (empty(frontend\models\News::$id_new)) {

    echo $form->field($model, 'id_news', ['inputOptions' => [ 'value' => \backend\models\Comment::$id_new]])
            ->hiddenInput() . \backend\models\Comment::$id_new . '<br><br>';
    
    echo $form->field($model, 'id_last', ['inputOptions' => [ 'value' => \backend\models\Comment::$id_coment]])
            ->hiddenInput() . \backend\models\Comment::$id_coment . '<br><br>';
    if (empty(Yii::$app->user->identity->username)) {
        echo $form->field($model, 'username')->textInput(['maxlength' => 255]);
    } else {
        echo $form->field($model, 'username', ['inputOptions' => [ 'value' => Yii::$app->user->identity->username]])
            ->hiddenInput() . '<strong>' . Yii::$app->user->identity->username . '</strong><br><br>';
    }
    if (empty(Yii::$app->user->identity->email)) {
        echo $form->field($model, 'email')->textInput();
    } else {
        echo $form->field($model, 'email', ['inputOptions' => [ 'value' => Yii::$app->user->identity->email]])
            ->hiddenInput() . '<strong>' . Yii::$app->user->identity->email . '</strong><br><br>';
    }
    //echo $form->field($model, 'status', ['inputOptions' => [ 'value' => 1]])->hiddenInput();
    echo $form->field($model, 'text')->textarea(['rows' => 6]);
    $model->mod = 0;
    
    echo Html::submitButton('Додати коментар', ['class' => 'btn btn-success']);
    
    ActiveForm::end(); ?>
</div>

advanced/backend/views/comment/comment-item.php
<?php
\backend\models\Comment::$id_new = $model['id_news'];
\backend\models\Comment::$id_coment = $model['id_com'];
$countcom = \backend\models\CommentSearch::commentNumberToNews($model->id_news);
$com_width = $com_width - 15;
$ncom = $model ['id_com'];
$status = Yii::$app->getRequest()->getQueryParams();
?>

<div>

    <?php
    echo Yii::$app->controller->renderPartial('comment-one', ['model' => $model]);

    if (empty($child)) {
        $child = \backend\models\CommentSearch::commentChild($model['id_news']);
    }

    if (!empty($child[$model['id_com']]['children'])) {
        foreach ($child[$model['id_com']]['children'] as $c) {
            ?>

            <div style="padding-left: 25px;">
                <?php
                $com_width = $com_width - 30;
                echo Yii::$app->controller->renderPartial('comment-item', ['model' => $c, 'child' => $child[$model['id_com']]['children']]);
                ?>
            </div> 
            <?php
        }
    }
    ?>
</div>

advanced/backend/views/comment/comment-one.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use demogorgorn\ajax\AjaxSubmitButton;

\backend\models\Comment::$id_new = $model['id_news'];
\backend\models\Comment::$id_coment = $model['id_com'];
$countcom = \backend\models\CommentSearch::commentNumberToNews($model->id_news);
$com_width = $com_width - 15;
$ncom = $model ['id_com'];
$status = Yii::$app->getRequest()->getQueryParams();

?>

<strong><?php echo $model ['username']; ?></strong><br>

<div id="text_<?php echo $model['id_com']; ?>">
    <?php
    echo Yii::$app->controller->renderPartial('comment-text', ['model' => $model]);
    ?>
</div>
<?php
echo Html::beginForm('', 'post', ['class' => 'uk-width-medium-1-1 uk-form uk-form-horizontal']);

echo Html::input('hidden', 'comment_id', $model['id_com']);

AjaxSubmitButton::begin([
    'label' => 'Статус',
    'ajaxOptions' => [
        'type' => 'POST',
        'url' => Url::toRoute(['comment/getinfo']),
        /* 'cache' => false, */
        'success' => new \yii\web\JsExpression('function(html){
            if (html == 1){
                $("#text_' . $model['id_com'] . '").children("span").css("color", "#333");
                }else{
                $("#text_' . $model['id_com'] . '").children("span").css("color", "#D3D3D3");
                }
            }'),
    ],
    'options' => ['class' => 'customclass', 'type' => 'submit'],
]);
AjaxSubmitButton::end();

echo Html::endForm();
?>
<a name="nach" id="ncom"></a> <a style="cursor:pointer;" onClick="showlayer('komm<?php echo $ncom ?>')">Прокоментувати</a>

<div id="komm<?php echo $ncom; ?>" style="display:none; padding:10px;  width:<?php echo $com_width; ?>;" align="left">
    <?php
    echo $model['id_com'];
    echo $this->render('/comment/create', ['model' => new \backend\models\Comment(),]);
    ?>
</div>

advanced/backend/views/comment/comment-text.php
<?php

use kartik\editable\Editable;


    ?>
    <span style="<?php if (empty($model['status'])):?> color:#D3D3D3 <?php endif;?>">
    <?php

echo 'IP: ' . $model['ip'] . '<br>';
    echo Editable::widget([
        'name' => "notes[{$model['id_com']}]",
        // 'displayValue' => '',
        'format' => Editable::FORMAT_BUTTON,
        'inputType' => Editable::INPUT_TEXTAREA,
        'value' => $model ['text'],
        'header' => 'Коментар',
        'submitOnEnter' => TRUE,
        'size' => 'lg',
        'id' => 'comment_text_' . $model['id_com'],
        'options' => [
            'class' => 'form-control', 'rows' => 5, 'placeholder' => 'Введіть текст...']
    ]);?>
</span>



 

advanced/backend/views/comment/comments.php
<?php

use yii\widgets\ListView;

echo ListView::widget([
    'dataProvider' => $dataProvider,
    'itemOptions' => ['class' => 'item'],
    'itemView' => function ($model, $key, $index, $widget) {
return Yii::$app->controller->renderPartial('comment-item', ['model' => $model]);
},
]);
?>

advanced/backend/views/comment/create.php
<?php

$this->title = 'Create Comment';
echo $this->render('addcom', [
    'model' => $model,
]);

?>

advanced/backend/views/comment/index.php
<?php

use yii\helpers\Html;
use yii\widgets\Pjax;

$this->title = 'Коментарі';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="comment-index">

    <h1><?php echo Html::encode($this->title); ?></h1>

    <?php
    echo $this->render('_search', ['model' => $searchModel]);

    \backend\models\Comment::$id_coment = '0';
    $countcom = \backend\models\CommentSearch::commentNumberToNews(\backend\models\Comment::$id_new);
    $com_width = \backend\models\Comment::$com_width;

    if (!empty($countcom)) {
        echo 'Коментарів: ' . $countcom;
    } else {
        echo 'Коментарів нема';
    }
    ?>
    <br>
    <a name="nach" id="ncom"></a> <a style="cursor:pointer;" onClick="showlayer('komm')">Прокоментувати</a>
    <br><br>
    <?php
    echo '<div id="komm" style="display:none; padding:10px;  width:' . $com_width . '-15px ;" align="left">';
    echo $this->render('/comment/create', ['model' => new \backend\models\Comment()]);
    echo '</div>';

    Pjax::begin([
        'id' => 'comments'
    ]);
    echo $comments;
    Pjax::end();
    ?>   










</div>

advanced/backend/views/comment/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Comment */

$this->title = $model->id_com;
$this->params['breadcrumbs'][] = ['label' => 'Comments', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="comment-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id_com], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id_com], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_com',
            'id_news',
            'id_last',
            'date_cr',
            'date_ed',
            'username',
            'ident',
            'email:ntext',
            'text:ntext',
            'mod',
        ],
    ]) ?>

</div>